name: get_mvc
description: "A Laravel Artisan like CLI tool for generating MVC files in Flutter projects for GetX."
version: 1.0.0
homepage: https://github.com/ignorantrahul/get_mvc
repository: https://github.com/ignorantrahul/get_mvc.git

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

executables:
  get_mvc: bin/get_mvc.dart
