name: get_mvc
description: A Laravel Artisan like CLI tool for generating MVC files in Flutter projects for get
homepage: https://github.com/ignorantrahul/get_mcv
version: 1.0.0
repository: https://github.com/ignorantrahul/get_mcv

environment:
  sdk: ">=3.0.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  dependencies:
  args: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  get_mvc: bin/get_mvc.dart
