name: get_mvc
description: "A Laravel Artisan like CLI tool for generating MVC files in Flutter projects for GetX."
version: 1.0.3
homepage: https://github.com/ignorantrahul/get_mvc
repository: https://github.com/ignorantrahul/get_mvc.git

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
